---
driver:
  name: vagrant
  provider: vmware_fusion

# provisioner:
#   hosts: test-kitchen
#   name: ansible_playbook
#   #roles_path: roles
#   require_ansible_repo: true
#   ansible_verbose: true
#   ansible_version: 2.9.4
#   require_chef_for_busser: false
#   playbook: site.yml

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default